version: '3.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'test1234'
      MYSQL_ROOT_PASSWORD: 'test1234'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql  
volumes:
  my-db:
