spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: localhost:9090
          predicates:
            - Path=/orders/**
      discovery:
        locator:
          enabled: true
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8012/eureka}
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability:
        1.0
jwt:
  secret: VHKJMNnbfhbsjkdbVJHVkhbJBKJBsmfnbngygiyguFYVHJbkjnjnsjdnlkfn