spring:
  application:
    name: order-service
  profiles:
    active: ${ACTIVE_PROFILES:local}
  cloud:
    config:
      uri: http://localhost:8086
  config:
    import: optional:configserver:http://localhost:8086

jwt:
  secret: VHKJMNnbfhbsjkdbVJHVkhbJBKJBsmfnbngygiyguFYVHJbkjnjnsjdnlkfn